version: 2
jobs:
  build:
    docker:
      # railsのruby verに合わせる
      - image: circleci/ruby:2.6.3
        # database.ymlとの設定差異に注意
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "study_graphql/Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # ディレクトリ構成が特殊なのでcdを使って移動してからbundle iする
      - run:
          name: install dependencies
          command: |
            cd study_graphql
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./study_graphql/vendor/bundle
          key: v1-dependencies-{{ checksum "study_graphql/Gemfile.lock" }}

      # Database setup
      - run:
          name: Database setup
          command: |
            cd study_graphql
            bundle exec rake db:create
            bundle exec rake db:migrate

      # run tests!
      - run:
          name: run tests
          command: |
            cd study_graphql
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
