name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_USERNAME: root
          MYSQL_ROOT_PASSWORD: P@ssw0rd

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Build and test with Rake
      run: |
        cd study_graphql
        sudo apt-get install libmysqlclient-dev
        gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/'
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rspec
